<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class DemoPermissionsTableSeeder extends Seeder
{
    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        \DB::table('permissions')->delete();

        \DB::table('permissions')->insert([
            0 => [
                'id' => 1,
                'name' => 'Create',
                'guard_name' => 'Expense Category Management',
                'slug' => 'expense-category-create',
                'created_at' => null,
                'updated_at' => null,
            ],
            1 => [
                'id' => 2,
                'name' => 'List',
                'guard_name' => 'Expense Category Management',
                'slug' => 'expense-category-list',
                'created_at' => null,
                'updated_at' => null,
            ],
            2 => [
                'id' => 3,
                'name' => 'Edit',
                'guard_name' => 'Expense Category Management',
                'slug' => 'expense-category-edit',
                'created_at' => null,
                'updated_at' => null,
            ],
            3 => [
                'id' => 4,
                'name' => 'Delete',
                'guard_name' => 'Expense Category Management',
                'slug' => 'expense-category-delete',
                'created_at' => null,
                'updated_at' => null,
            ],
            4 => [
                'id' => 5,
                'name' => 'Create',
                'guard_name' => 'Expense Subcategory Management',
                'slug' => 'expense-sub-category-create',
                'created_at' => null,
                'updated_at' => null,
            ],
            5 => [
                'id' => 6,
                'name' => 'List',
                'guard_name' => 'Expense Subcategory Management',
                'slug' => 'expense-sub-category-list',
                'created_at' => null,
                'updated_at' => null,
            ],
            6 => [
                'id' => 7,
                'name' => 'Edit',
                'guard_name' => 'Expense Subcategory Management',
                'slug' => 'expense-sub-category-edit',
                'created_at' => null,
                'updated_at' => null,
            ],
            7 => [
                'id' => 8,
                'name' => 'Delete',
                'guard_name' => 'Expense Subcategory Management',
                'slug' => 'expense-sub-category-delete',
                'created_at' => null,
                'updated_at' => null,
            ],
            8 => [
                'id' => 9,
                'name' => 'Create',
                'guard_name' => 'Expense Management',
                'slug' => 'expense-create',
                'created_at' => null,
                'updated_at' => null,
            ],
            9 => [
                'id' => 10,
                'name' => 'List',
                'guard_name' => 'Expense Management',
                'slug' => 'expense-list',
                'created_at' => null,
                'updated_at' => null,
            ],
            10 => [
                'id' => 11,
                'name' => 'Edit',
                'guard_name' => 'Expense Management',
                'slug' => 'expense-edit',
                'created_at' => null,
                'updated_at' => null,
            ],
            11 => [
                'id' => 12,
                'name' => 'View',
                'guard_name' => 'Expense Management',
                'slug' => 'expense-view',
                'created_at' => null,
                'updated_at' => null,
            ],
            12 => [
                'id' => 13,
                'name' => 'Delete',
                'guard_name' => 'Expense Management',
                'slug' => 'expense-delete',
                'created_at' => null,
                'updated_at' => '2022-05-15 09:21:37',
            ],
            13 => [
                'id' => 14,
                'name' => 'Create',
                'guard_name' => 'Purchase Management',
                'slug' => 'purchase-create',
                'created_at' => null,
                'updated_at' => null,
            ],
            14 => [
                'id' => 15,
                'name' => 'List',
                'guard_name' => 'Purchase Management',
                'slug' => 'purchase-list',
                'created_at' => null,
                'updated_at' => null,
            ],
            15 => [
                'id' => 16,
                'name' => 'Edit',
                'guard_name' => 'Purchase Management',
                'slug' => 'purchase-edit',
                'created_at' => null,
                'updated_at' => null,
            ],
            16 => [
                'id' => 17,
                'name' => 'View',
                'guard_name' => 'Purchase Management',
                'slug' => 'purchase-view',
                'created_at' => null,
                'updated_at' => null,
            ],
            17 => [
                'id' => 18,
                'name' => 'Delete',
                'guard_name' => 'Purchase Management',
                'slug' => 'purchase-delete',
                'created_at' => null,
                'updated_at' => null,
            ],
            18 => [
                'id' => 19,
                'name' => 'Create',
                'guard_name' => 'Purchase Return Management',
                'slug' => 'purchase-return-create',
                'created_at' => null,
                'updated_at' => null,
            ],
            19 => [
                'id' => 20,
                'name' => 'List',
                'guard_name' => 'Purchase Return Management',
                'slug' => 'purchase-return-list',
                'created_at' => null,
                'updated_at' => null,
            ],
            20 => [
                'id' => 21,
                'name' => 'Edit',
                'guard_name' => 'Purchase Return Management',
                'slug' => 'purchase-return-edit',
                'created_at' => null,
                'updated_at' => null,
            ],
            21 => [
                'id' => 22,
                'name' => 'View',
                'guard_name' => 'Purchase Return Management',
                'slug' => 'purchase-return-view',
                'created_at' => null,
                'updated_at' => null,
            ],
            22 => [
                'id' => 23,
                'name' => 'Delete',
                'guard_name' => 'Purchase Return Management',
                'slug' => 'purchase-return-delete',
                'created_at' => null,
                'updated_at' => null,
            ],
            23 => [
                'id' => 24,
                'name' => 'Create',
                'guard_name' => 'Quotation Management',
                'slug' => 'quotation-create',
                'created_at' => null,
                'updated_at' => null,
            ],
            24 => [
                'id' => 25,
                'name' => 'List',
                'guard_name' => 'Quotation Management',
                'slug' => 'quotation-list',
                'created_at' => null,
                'updated_at' => null,
            ],
            25 => [
                'id' => 26,
                'name' => 'Edit',
                'guard_name' => 'Quotation Management',
                'slug' => 'quotation-edit',
                'created_at' => null,
                'updated_at' => null,
            ],
            26 => [
                'id' => 27,
                'name' => 'View',
                'guard_name' => 'Quotation Management',
                'slug' => 'quotation-view',
                'created_at' => null,
                'updated_at' => null,
            ],
            27 => [
                'id' => 28,
                'name' => 'Delete',
                'guard_name' => 'Quotation Management',
                'slug' => 'quotation-delete',
                'created_at' => null,
                'updated_at' => null,
            ],
            28 => [
                'id' => 29,
                'name' => 'Quotation to Invoice',
                'guard_name' => 'Quotation Management',
                'slug' => 'quotation-to-invoice',
                'created_at' => null,
                'updated_at' => null,
            ],
            29 => [
                'id' => 30,
                'name' => 'Create',
                'guard_name' => 'Invoice Management',
                'slug' => 'invoice-create',
                'created_at' => null,
                'updated_at' => null,
            ],
            30 => [
                'id' => 31,
                'name' => 'List',
                'guard_name' => 'Invoice Management',
                'slug' => 'invoice-list',
                'created_at' => null,
                'updated_at' => null,
            ],
            31 => [
                'id' => 32,
                'name' => 'Edit',
                'guard_name' => 'Invoice Management',
                'slug' => 'invoice-edit',
                'created_at' => null,
                'updated_at' => null,
            ],
            32 => [
                'id' => 33,
                'name' => 'View',
                'guard_name' => 'Invoice Management',
                'slug' => 'invoice-view',
                'created_at' => null,
                'updated_at' => null,
            ],
            33 => [
                'id' => 34,
                'name' => 'Delete',
                'guard_name' => 'Invoice Management',
                'slug' => 'invoice-delete',
                'created_at' => null,
                'updated_at' => null,
            ],
            34 => [
                'id' => 35,
                'name' => 'Create',
                'guard_name' => 'Invoice Return Management',
                'slug' => 'invoice-return-create',
                'created_at' => null,
                'updated_at' => null,
            ],
            35 => [
                'id' => 36,
                'name' => 'List',
                'guard_name' => 'Invoice Return Management',
                'slug' => 'invoice-return-list',
                'created_at' => null,
                'updated_at' => null,
            ],
            36 => [
                'id' => 37,
                'name' => 'Edit',
                'guard_name' => 'Invoice Return Management',
                'slug' => 'invoice-return-edit',
                'created_at' => null,
                'updated_at' => null,
            ],
            37 => [
                'id' => 38,
                'name' => 'View',
                'guard_name' => 'Invoice Return Management',
                'slug' => 'invoice-return-view',
                'created_at' => null,
                'updated_at' => null,
            ],
            38 => [
                'id' => 39,
                'name' => 'Delete',
                'guard_name' => 'Invoice Return Management',
                'slug' => 'invoice-return-delete',
                'created_at' => null,
                'updated_at' => null,
            ],
            39 => [
                'id' => 40,
                'name' => 'Create',
                'guard_name' => 'Account Management',
                'slug' => 'account-create',
                'created_at' => null,
                'updated_at' => null,
            ],
            40 => [
                'id' => 41,
                'name' => 'List',
                'guard_name' => 'Account Management',
                'slug' => 'account-list',
                'created_at' => null,
                'updated_at' => null,
            ],
            41 => [
                'id' => 42,
                'name' => 'Edit',
                'guard_name' => 'Account Management',
                'slug' => 'account-edit',
                'created_at' => null,
                'updated_at' => null,
            ],
            42 => [
                'id' => 43,
                'name' => 'View',
                'guard_name' => 'Account Management',
                'slug' => 'account-view',
                'created_at' => null,
                'updated_at' => null,
            ],
            43 => [
                'id' => 44,
                'name' => 'Delete',
                'guard_name' => 'Account Management',
                'slug' => 'account-delete',
                'created_at' => null,
                'updated_at' => null,
            ],
            44 => [
                'id' => 45,
                'name' => 'Create',
                'guard_name' => 'Account Balance Management',
                'slug' => 'account-balance-create',
                'created_at' => null,
                'updated_at' => null,
            ],
            45 => [
                'id' => 46,
                'name' => 'List',
                'guard_name' => 'Account Balance Management',
                'slug' => 'account-balance-list',
                'created_at' => null,
                'updated_at' => null,
            ],
            46 => [
                'id' => 47,
                'name' => 'Edit',
                'guard_name' => 'Account Balance Management',
                'slug' => 'account-balance-edit',
                'created_at' => null,
                'updated_at' => null,
            ],
            47 => [
                'id' => 48,
                'name' => 'Delete',
                'guard_name' => 'Account Balance Management',
                'slug' => 'account-balance-delete',
                'created_at' => null,
                'updated_at' => null,
            ],
            48 => [
                'id' => 49,
                'name' => 'Create',
                'guard_name' => 'Balance Transfer Management',
                'slug' => 'account-transfer-balance-create',
                'created_at' => null,
                'updated_at' => null,
            ],
            49 => [
                'id' => 50,
                'name' => 'List',
                'guard_name' => 'Balance Transfer Management',
                'slug' => 'account-transfer-balance-list',
                'created_at' => null,
                'updated_at' => null,
            ],
            50 => [
                'id' => 51,
                'name' => 'Edit',
                'guard_name' => 'Balance Transfer Management',
                'slug' => 'account-transfer-balance-edit',
                'created_at' => null,
                'updated_at' => null,
            ],
            51 => [
                'id' => 52,
                'name' => 'View',
                'guard_name' => 'Balance Transfer Management',
                'slug' => 'account-transfer-balance-view',
                'created_at' => null,
                'updated_at' => null,
            ],
            52 => [
                'id' => 53,
                'name' => 'Delete',
                'guard_name' => 'Balance Transfer Management',
                'slug' => 'account-transfer-balance-delete',
                'created_at' => null,
                'updated_at' => null,
            ],
            53 => [
                'id' => 54,
                'name' => 'Create',
                'guard_name' => 'Non Purchase Payment Management',
                'slug' => 'non-purchase-payment-create',
                'created_at' => null,
                'updated_at' => null,
            ],
            54 => [
                'id' => 55,
                'name' => 'List',
                'guard_name' => 'Non Purchase Payment Management',
                'slug' => 'non-purchase-payment-list',
                'created_at' => null,
                'updated_at' => null,
            ],
            55 => [
                'id' => 56,
                'name' => 'Edit',
                'guard_name' => 'Non Purchase Payment Management',
                'slug' => 'non-purchase-payment-edit',
                'created_at' => null,
                'updated_at' => null,
            ],
            56 => [
                'id' => 57,
                'name' => 'View',
                'guard_name' => 'Non Purchase Payment Management',
                'slug' => 'non-purchase-payment-view',
                'created_at' => null,
                'updated_at' => null,
            ],
            57 => [
                'id' => 58,
                'name' => 'Delete',
                'guard_name' => 'Non Purchase Payment Management',
                'slug' => 'non-purchase-payment-delete',
                'created_at' => null,
                'updated_at' => null,
            ],
            58 => [
                'id' => 59,
                'name' => 'Create',
                'guard_name' => 'Purchase Payment Management',
                'slug' => 'purchase-payment-create',
                'created_at' => null,
                'updated_at' => null,
            ],
            59 => [
                'id' => 60,
                'name' => 'List',
                'guard_name' => 'Purchase Payment Management',
                'slug' => 'purchase-payment-list',
                'created_at' => null,
                'updated_at' => null,
            ],
            60 => [
                'id' => 61,
                'name' => 'Edit',
                'guard_name' => 'Purchase Payment Management',
                'slug' => 'purchase-payment-edit',
                'created_at' => null,
                'updated_at' => null,
            ],
            61 => [
                'id' => 62,
                'name' => 'View',
                'guard_name' => 'Purchase Payment Management',
                'slug' => 'purchase-payment-view',
                'created_at' => null,
                'updated_at' => null,
            ],
            62 => [
                'id' => 63,
                'name' => 'Delete',
                'guard_name' => 'Purchase Payment Management',
                'slug' => 'purchase-payment-delete',
                'created_at' => null,
                'updated_at' => null,
            ],
            63 => [
                'id' => 64,
                'name' => 'Create',
                'guard_name' => 'Non Invoice Payment Management',
                'slug' => 'non-invoice-payment-create',
                'created_at' => null,
                'updated_at' => null,
            ],
            64 => [
                'id' => 65,
                'name' => 'List',
                'guard_name' => 'Non Invoice Payment Management',
                'slug' => 'non-invoice-payment-list',
                'created_at' => null,
                'updated_at' => null,
            ],
            65 => [
                'id' => 66,
                'name' => 'Edit',
                'guard_name' => 'Non Invoice Payment Management',
                'slug' => 'non-invoice-payment-edit',
                'created_at' => null,
                'updated_at' => null,
            ],
            66 => [
                'id' => 67,
                'name' => 'View',
                'guard_name' => 'Non Invoice Payment Management',
                'slug' => 'non-invoice-payment-view',
                'created_at' => null,
                'updated_at' => null,
            ],
            67 => [
                'id' => 68,
                'name' => 'Delete',
                'guard_name' => 'Non Invoice Payment Management',
                'slug' => 'non-invoice-payment-delete',
                'created_at' => null,
                'updated_at' => null,
            ],
            68 => [
                'id' => 69,
                'name' => 'Create',
                'guard_name' => 'Invoice Payment Management',
                'slug' => 'invoice-payment-create',
                'created_at' => null,
                'updated_at' => null,
            ],
            69 => [
                'id' => 70,
                'name' => 'List',
                'guard_name' => 'Invoice Payment Management',
                'slug' => 'invoice-payment-list',
                'created_at' => null,
                'updated_at' => null,
            ],
            70 => [
                'id' => 71,
                'name' => 'Edit',
                'guard_name' => 'Invoice Payment Management',
                'slug' => 'invoice-payment-edit',
                'created_at' => null,
                'updated_at' => null,
            ],
            71 => [
                'id' => 72,
                'name' => 'View',
                'guard_name' => 'Invoice Payment Management',
                'slug' => 'invoice-payment-view',
                'created_at' => null,
                'updated_at' => null,
            ],
            72 => [
                'id' => 73,
                'name' => 'Delete',
                'guard_name' => 'Invoice Payment Management',
                'slug' => 'invoice-payment-delete',
                'created_at' => null,
                'updated_at' => null,
            ],
            73 => [
                'id' => 74,
                'name' => 'Create',
                'guard_name' => 'Loan Authority Management',
                'slug' => 'loan-authority-create',
                'created_at' => null,
                'updated_at' => null,
            ],
            74 => [
                'id' => 75,
                'name' => 'List',
                'guard_name' => 'Loan Authority Management',
                'slug' => 'loan-authority-list',
                'created_at' => null,
                'updated_at' => null,
            ],
            75 => [
                'id' => 76,
                'name' => 'Edit',
                'guard_name' => 'Loan Authority Management',
                'slug' => 'loan-authority-edit',
                'created_at' => null,
                'updated_at' => null,
            ],
            76 => [
                'id' => 77,
                'name' => 'View',
                'guard_name' => 'Loan Authority Management',
                'slug' => 'loan-authority-view',
                'created_at' => null,
                'updated_at' => null,
            ],
            77 => [
                'id' => 78,
                'name' => 'Delete',
                'guard_name' => 'Loan Authority Management',
                'slug' => 'loan-authority-delete',
                'created_at' => null,
                'updated_at' => null,
            ],
            78 => [
                'id' => 79,
                'name' => 'Create',
                'guard_name' => 'Loan Management',
                'slug' => 'loan-create',
                'created_at' => null,
                'updated_at' => null,
            ],
            79 => [
                'id' => 80,
                'name' => 'List',
                'guard_name' => 'Loan Management',
                'slug' => 'loan-list',
                'created_at' => null,
                'updated_at' => null,
            ],
            80 => [
                'id' => 81,
                'name' => 'Edit',
                'guard_name' => 'Loan Management',
                'slug' => 'loan-edit',
                'created_at' => null,
                'updated_at' => null,
            ],
            81 => [
                'id' => 82,
                'name' => 'View',
                'guard_name' => 'Loan Management',
                'slug' => 'loan-view',
                'created_at' => null,
                'updated_at' => null,
            ],
            82 => [
                'id' => 83,
                'name' => 'Delete',
                'guard_name' => 'Loan Management',
                'slug' => 'loan-delete',
                'created_at' => null,
                'updated_at' => null,
            ],
            83 => [
                'id' => 84,
                'name' => 'Create',
                'guard_name' => 'Loan Payment Management',
                'slug' => 'loan-payment-create',
                'created_at' => null,
                'updated_at' => null,
            ],
            84 => [
                'id' => 85,
                'name' => 'List',
                'guard_name' => 'Loan Payment Management',
                'slug' => 'loan-payment-list',
                'created_at' => null,
                'updated_at' => null,
            ],
            85 => [
                'id' => 86,
                'name' => 'Edit',
                'guard_name' => 'Loan Payment Management',
                'slug' => 'loan-payment-edit',
                'created_at' => null,
                'updated_at' => null,
            ],
            86 => [
                'id' => 87,
                'name' => 'View',
                'guard_name' => 'Loan Payment Management',
                'slug' => 'loan-payment-view',
                'created_at' => null,
                'updated_at' => null,
            ],
            87 => [
                'id' => 88,
                'name' => 'Delete',
                'guard_name' => 'Loan Payment Management',
                'slug' => 'loan-payment-delete',
                'created_at' => null,
                'updated_at' => null,
            ],
            88 => [
                'id' => 89,
                'name' => 'Create',
                'guard_name' => 'Asset Type Management',
                'slug' => 'asset-type-create',
                'created_at' => null,
                'updated_at' => null,
            ],
            89 => [
                'id' => 90,
                'name' => 'List',
                'guard_name' => 'Asset Type Management',
                'slug' => 'asset-type-list',
                'created_at' => null,
                'updated_at' => null,
            ],
            90 => [
                'id' => 91,
                'name' => 'Edit',
                'guard_name' => 'Asset Type Management',
                'slug' => 'asset-type-edit',
                'created_at' => null,
                'updated_at' => null,
            ],
            91 => [
                'id' => 92,
                'name' => 'Delete',
                'guard_name' => 'Asset Type Management',
                'slug' => 'asset-type-delete',
                'created_at' => null,
                'updated_at' => null,
            ],
            92 => [
                'id' => 93,
                'name' => 'Create',
                'guard_name' => 'Asset Management',
                'slug' => 'asset-create',
                'created_at' => null,
                'updated_at' => null,
            ],
            93 => [
                'id' => 94,
                'name' => 'List',
                'guard_name' => 'Asset Management',
                'slug' => 'asset-list',
                'created_at' => null,
                'updated_at' => null,
            ],
            94 => [
                'id' => 95,
                'name' => 'Edit',
                'guard_name' => 'Asset Management',
                'slug' => 'asset-edit',
                'created_at' => null,
                'updated_at' => null,
            ],
            95 => [
                'id' => 96,
                'name' => 'View',
                'guard_name' => 'Asset Management',
                'slug' => 'asset-view',
                'created_at' => null,
                'updated_at' => null,
            ],
            96 => [
                'id' => 97,
                'name' => 'Delete',
                'guard_name' => 'Asset Management',
                'slug' => 'asset-delete',
                'created_at' => null,
                'updated_at' => null,
            ],
            97 => [
                'id' => 98,
                'name' => 'Create',
                'guard_name' => 'Payroll Management',
                'slug' => 'payroll-create',
                'created_at' => null,
                'updated_at' => null,
            ],
            98 => [
                'id' => 99,
                'name' => 'List',
                'guard_name' => 'Payroll Management',
                'slug' => 'payroll-list',
                'created_at' => null,
                'updated_at' => null,
            ],
            99 => [
                'id' => 100,
                'name' => 'Edit',
                'guard_name' => 'Payroll Management',
                'slug' => 'payroll-edit',
                'created_at' => null,
                'updated_at' => null,
            ],
            100 => [
                'id' => 101,
                'name' => 'View',
                'guard_name' => 'Payroll Management',
                'slug' => 'payroll-view',
                'created_at' => null,
                'updated_at' => null,
            ],
            101 => [
                'id' => 102,
                'name' => 'Delete',
                'guard_name' => 'Payroll Management',
                'slug' => 'payroll-delete',
                'created_at' => null,
                'updated_at' => null,
            ],
            102 => [
                'id' => 103,
                'name' => 'Create',
                'guard_name' => 'Client Management',
                'slug' => 'client-create',
                'created_at' => null,
                'updated_at' => null,
            ],
            103 => [
                'id' => 104,
                'name' => 'List',
                'guard_name' => 'Client Management',
                'slug' => 'client-list',
                'created_at' => null,
                'updated_at' => null,
            ],
            104 => [
                'id' => 105,
                'name' => 'Edit',
                'guard_name' => 'Client Management',
                'slug' => 'client-edit',
                'created_at' => null,
                'updated_at' => null,
            ],
            105 => [
                'id' => 106,
                'name' => 'View',
                'guard_name' => 'Client Management',
                'slug' => 'client-view',
                'created_at' => null,
                'updated_at' => null,
            ],
            106 => [
                'id' => 107,
                'name' => 'Delete',
                'guard_name' => 'Client Management',
                'slug' => 'client-delete',
                'created_at' => null,
                'updated_at' => null,
            ],
            107 => [
                'id' => 108,
                'name' => 'Create',
                'guard_name' => 'Supplier Management',
                'slug' => 'supplier-create',
                'created_at' => null,
                'updated_at' => null,
            ],
            108 => [
                'id' => 109,
                'name' => 'List',
                'guard_name' => 'Supplier Management',
                'slug' => 'supplier-list',
                'created_at' => null,
                'updated_at' => null,
            ],
            109 => [
                'id' => 110,
                'name' => 'Edit',
                'guard_name' => 'Supplier Management',
                'slug' => 'supplier-edit',
                'created_at' => null,
                'updated_at' => null,
            ],
            110 => [
                'id' => 111,
                'name' => 'View',
                'guard_name' => 'Supplier Management',
                'slug' => 'supplier-view',
                'created_at' => null,
                'updated_at' => null,
            ],
            111 => [
                'id' => 112,
                'name' => 'Delete',
                'guard_name' => 'Supplier Management',
                'slug' => 'supplier-delete',
                'created_at' => null,
                'updated_at' => null,
            ],
            112 => [
                'id' => 113,
                'name' => 'Create',
                'guard_name' => 'Department Management',
                'slug' => 'department-create',
                'created_at' => null,
                'updated_at' => null,
            ],
            113 => [
                'id' => 114,
                'name' => 'List',
                'guard_name' => 'Department Management',
                'slug' => 'department-list',
                'created_at' => null,
                'updated_at' => null,
            ],
            114 => [
                'id' => 115,
                'name' => 'Edit',
                'guard_name' => 'Department Management',
                'slug' => 'department-edit',
                'created_at' => null,
                'updated_at' => null,
            ],
            115 => [
                'id' => 116,
                'name' => 'Delete',
                'guard_name' => 'Department Management',
                'slug' => 'department-delete',
                'created_at' => null,
                'updated_at' => null,
            ],
            116 => [
                'id' => 117,
                'name' => 'Create',
                'guard_name' => 'Employee Management',
                'slug' => 'employee-create',
                'created_at' => null,
                'updated_at' => null,
            ],
            117 => [
                'id' => 118,
                'name' => 'List',
                'guard_name' => 'Employee Management',
                'slug' => 'employee-list',
                'created_at' => null,
                'updated_at' => null,
            ],
            118 => [
                'id' => 119,
                'name' => 'Edit',
                'guard_name' => 'Employee Management',
                'slug' => 'employee-edit',
                'created_at' => null,
                'updated_at' => null,
            ],
            119 => [
                'id' => 120,
                'name' => 'View',
                'guard_name' => 'Employee Management',
                'slug' => 'employee-view',
                'created_at' => null,
                'updated_at' => null,
            ],
            120 => [
                'id' => 121,
                'name' => 'Delete',
                'guard_name' => 'Employee Management',
                'slug' => 'employee-delete',
                'created_at' => null,
                'updated_at' => null,
            ],
            121 => [
                'id' => 122,
                'name' => 'Create',
                'guard_name' => 'Increment Management',
                'slug' => 'increment-create',
                'created_at' => null,
                'updated_at' => null,
            ],
            122 => [
                'id' => 123,
                'name' => 'List',
                'guard_name' => 'Increment Management',
                'slug' => 'increment-list',
                'created_at' => null,
                'updated_at' => null,
            ],
            123 => [
                'id' => 124,
                'name' => 'Edit',
                'guard_name' => 'Increment Management',
                'slug' => 'increment-edit',
                'created_at' => null,
                'updated_at' => null,
            ],
            124 => [
                'id' => 125,
                'name' => 'View',
                'guard_name' => 'Increment Management',
                'slug' => 'increment-view',
                'created_at' => null,
                'updated_at' => null,
            ],
            125 => [
                'id' => 126,
                'name' => 'Delete',
                'guard_name' => 'Increment Management',
                'slug' => 'increment-delete',
                'created_at' => null,
                'updated_at' => null,
            ],
            126 => [
                'id' => 127,
                'name' => 'Create',
                'guard_name' => 'Product Category Management',
                'slug' => 'product-category-create',
                'created_at' => null,
                'updated_at' => null,
            ],
            127 => [
                'id' => 128,
                'name' => 'List',
                'guard_name' => 'Product Category Management',
                'slug' => 'product-category-list',
                'created_at' => null,
                'updated_at' => null,
            ],
            128 => [
                'id' => 129,
                'name' => 'Edit',
                'guard_name' => 'Product Category Management',
                'slug' => 'product-category-edit',
                'created_at' => null,
                'updated_at' => null,
            ],
            129 => [
                'id' => 130,
                'name' => 'Delete',
                'guard_name' => 'Product Category Management',
                'slug' => 'product-category-delete',
                'created_at' => null,
                'updated_at' => null,
            ],
            130 => [
                'id' => 131,
                'name' => 'Create',
                'guard_name' => 'Product Subcategory Management',
                'slug' => 'product-sub-category-create',
                'created_at' => null,
                'updated_at' => null,
            ],
            131 => [
                'id' => 132,
                'name' => 'List',
                'guard_name' => 'Product Subcategory Management',
                'slug' => 'product-sub-category-list',
                'created_at' => null,
                'updated_at' => null,
            ],
            132 => [
                'id' => 133,
                'name' => 'Edit',
                'guard_name' => 'Product Subcategory Management',
                'slug' => 'product-sub-category-edit',
                'created_at' => null,
                'updated_at' => null,
            ],
            133 => [
                'id' => 134,
                'name' => 'Delete',
                'guard_name' => 'Product Subcategory Management',
                'slug' => 'product-sub-category-delete',
                'created_at' => null,
                'updated_at' => null,
            ],
            134 => [
                'id' => 135,
                'name' => 'Create',
                'guard_name' => 'Product Management',
                'slug' => 'product-create',
                'created_at' => null,
                'updated_at' => null,
            ],
            135 => [
                'id' => 136,
                'name' => 'List',
                'guard_name' => 'Product Management',
                'slug' => 'product-list',
                'created_at' => null,
                'updated_at' => null,
            ],
            136 => [
                'id' => 137,
                'name' => 'Edit',
                'guard_name' => 'Product Management',
                'slug' => 'product-edit',
                'created_at' => null,
                'updated_at' => null,
            ],
            137 => [
                'id' => 138,
                'name' => 'View',
                'guard_name' => 'Product Management',
                'slug' => 'product-view',
                'created_at' => null,
                'updated_at' => null,
            ],
            138 => [
                'id' => 139,
                'name' => 'Delete',
                'guard_name' => 'Product Management',
                'slug' => 'product-delete',
                'created_at' => null,
                'updated_at' => null,
            ],
            139 => [
                'id' => 140,
                'name' => 'History',
                'guard_name' => 'Inventory Management',
                'slug' => 'inventory-history',
                'created_at' => null,
                'updated_at' => null,
            ],
            140 => [
                'id' => 141,
                'name' => 'View',
                'guard_name' => 'Inventory Management',
                'slug' => 'inventory-view',
                'created_at' => null,
                'updated_at' => null,
            ],
            141 => [
                'id' => 142,
                'name' => 'Create',
                'guard_name' => 'Inventory Adjustment Management',
                'slug' => 'adjustment-create',
                'created_at' => null,
                'updated_at' => null,
            ],
            142 => [
                'id' => 143,
                'name' => 'List',
                'guard_name' => 'Inventory Adjustment Management',
                'slug' => 'adjustment-list',
                'created_at' => null,
                'updated_at' => null,
            ],
            143 => [
                'id' => 144,
                'name' => 'Edit',
                'guard_name' => 'Inventory Adjustment Management',
                'slug' => 'adjustment-edit',
                'created_at' => null,
                'updated_at' => null,
            ],
            144 => [
                'id' => 145,
                'name' => 'View',
                'guard_name' => 'Inventory Adjustment Management',
                'slug' => 'adjustment-view',
                'created_at' => null,
                'updated_at' => null,
            ],
            145 => [
                'id' => 146,
                'name' => 'Delete',
                'guard_name' => 'Inventory Adjustment Management',
                'slug' => 'adjustment-delete',
                'created_at' => null,
                'updated_at' => null,
            ],
            146 => [
                'id' => 147,
                'name' => 'Print Barcode',
                'guard_name' => 'Extra Management',
                'slug' => 'print-barcode',
                'created_at' => null,
                'updated_at' => null,
            ],
            147 => [
                'id' => 148,
                'name' => 'Transaction History',
                'guard_name' => 'Extra Management',
                'slug' => 'transaction-history',
                'created_at' => null,
                'updated_at' => null,
            ],
            148 => [
                'id' => 149,
                'name' => 'Database Backup',
                'guard_name' => 'Extra Management',
                'slug' => 'database-backup',
                'created_at' => null,
                'updated_at' => null,
            ],
            149 => [
                'id' => 150,
                'name' => 'Update Profile',
                'guard_name' => 'Extra Management',
                'slug' => 'update-profile',
                'created_at' => null,
                'updated_at' => null,
            ],
            150 => [
                'id' => 151,
                'name' => 'Balance Sheet',
                'guard_name' => 'Report View',
                'slug' => 'balance-sheet',
                'created_at' => null,
                'updated_at' => null,
            ],
            151 => [
                'id' => 152,
                'name' => 'Summary Report',
                'guard_name' => 'Report View',
                'slug' => 'summary-report',
                'created_at' => null,
                'updated_at' => null,
            ],
            152 => [
                'id' => 153,
                'name' => 'Profit/Loss',
                'guard_name' => 'Report View',
                'slug' => 'profit-loss',
                'created_at' => null,
                'updated_at' => null,
            ],
            153 => [
                'id' => 154,
                'name' => 'Expense Report',
                'guard_name' => 'Report View',
                'slug' => 'expense-report',
                'created_at' => null,
                'updated_at' => null,
            ],
            154 => [
                'id' => 155,
                'name' => 'Item Report',
                'guard_name' => 'Report View',
                'slug' => 'item-report',
                'created_at' => null,
                'updated_at' => null,
            ],
            155 => [
                'id' => 156,
                'name' => 'Inventory Report',
                'guard_name' => 'Report View',
                'slug' => 'inventory-report',
                'created_at' => null,
                'updated_at' => null,
            ],
            156 => [
                'id' => 157,
                'name' => 'General settings',
                'guard_name' => 'Setup',
                'slug' => 'general-settings',
                'created_at' => null,
                'updated_at' => null,
            ],
            157 => [
                'id' => 158,
                'name' => 'Permissions management',
                'guard_name' => 'Setup',
                'slug' => 'user-permission',
                'created_at' => null,
                'updated_at' => null,
            ],
            158 => [
                'id' => 159,
                'name' => 'Roles Management',
                'guard_name' => 'Setup',
                'slug' => 'user-role',
                'created_at' => null,
                'updated_at' => null,
            ],
            159 => [
                'id' => 160,
                'name' => 'Units management',
                'guard_name' => 'Setup',
                'slug' => 'units-management',
                'created_at' => null,
                'updated_at' => null,
            ],
            160 => [
                'id' => 161,
                'name' => 'Currencies Management',
                'guard_name' => 'Setup',
                'slug' => 'currencies-management',
                'created_at' => null,
                'updated_at' => null,
            ],
            161 => [
                'id' => 162,
                'name' => 'Brands Management',
                'guard_name' => 'Setup',
                'slug' => 'brands-management',
                'created_at' => null,
                'updated_at' => null,
            ],
            162 => [
                'id' => 163,
                'name' => 'Payment Method Management',
                'guard_name' => 'Setup',
                'slug' => 'payment-method-management',
                'created_at' => null,
                'updated_at' => null,
            ],
            163 => [
                'id' => 164,
                'name' => 'VAT Rate Management',
                'guard_name' => 'Setup',
                'slug' => 'vat-rate-management',
                'created_at' => null,
                'updated_at' => null,
            ],
            164 => [
                'id' => 165,
                'name' => 'Account Summery',
                'guard_name' => 'Dashboard View',
                'slug' => 'account-summery',
                'created_at' => null,
                'updated_at' => null,
            ],
            165 => [
                'id' => 166,
                'name' => 'Top Selling Products',
                'guard_name' => 'Dashboard View',
                'slug' => 'top-selling-products',
                'created_at' => null,
                'updated_at' => null,
            ],
            166 => [
                'id' => 167,
                'name' => 'Recent Activities',
                'guard_name' => 'Dashboard View',
                'slug' => 'recent-activities',
                'created_at' => null,
                'updated_at' => null,
            ],
            167 => [
                'id' => 168,
                'name' => 'Payment Sent vs Payment Received',
                'guard_name' => 'Dashboard View',
                'slug' => 'payment-sent-vs-payment-received',
                'created_at' => null,
                'updated_at' => null,
            ],
            168 => [
                'id' => 169,
                'name' => 'Top Clients',
                'guard_name' => 'Dashboard View',
                'slug' => 'top-clients',
                'created_at' => null,
                'updated_at' => null,
            ],
            169 => [
                'id' => 170,
                'name' => 'Stock Alert',
                'guard_name' => 'Dashboard View',
                'slug' => 'stock-alert',
                'created_at' => null,
                'updated_at' => null,
            ],
            170 => [
                'id' => 171,
                'name' => 'Sales vs Purchases',
                'guard_name' => 'Dashboard View',
                'slug' => 'sales-vs-purchases',
                'created_at' => null,
                'updated_at' => null,
            ],
            171 => [
                'id' => 172,
                'name' => 'Mail Configuration',
                'guard_name' => 'Setup',
                'slug' => 'mail-configuration',
                'created_at' => null,
                'updated_at' => null,
            ],
            172 => [
                'id' => 173,
                'name' => 'SMS Configuration',
                'guard_name' => 'Setup',
                'slug' => 'sms-configuration',
                'created_at' => null,
                'updated_at' => null,
            ],
        ]);
    }
}
