<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class DemoAccountTransactionsTableSeeder extends Seeder
{
    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        \DB::table('account_transactions')->delete();

        \DB::table('account_transactions')->insert([
            0 => [
                'id' => 1,
                'reason' => 'Non invoice balance added to [CASH-0001]',
                'slug' => 'non-invoice-balance-added-to-cash-0001',
                'amount' => 100000.0,
                'type' => 1,
                'cheque_no' => null,
                'receipt_no' => null,
                'transaction_date' => now(),
                'note' => null,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'account_id' => 1,
                'created_by' => 1,
            ],
            1 => [
                'id' => 2,
                'reason' => 'Non invoice balance added to [IBBL-0002]',
                'slug' => 'non-invoice-balance-added-to-ibbl-0002',
                'amount' => 100000.0,
                'type' => 1,
                'cheque_no' => null,
                'receipt_no' => null,
                'transaction_date' => now(),
                'note' => null,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'account_id' => 3,
                'created_by' => 1,
            ],
            2 => [
                'id' => 3,
                'reason' => 'Non invoice balance added to [DBBL-0003]',
                'slug' => 'non-invoice-balance-added-to-dbbl-0003',
                'amount' => 100000.0,
                'type' => 1,
                'cheque_no' => null,
                'receipt_no' => null,
                'transaction_date' => now(),
                'note' => null,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'account_id' => 2,
                'created_by' => 1,
            ],
            3 => [
                'id' => 4,
                'reason' => 'Balance transfer from [CASH-0001]',
                'slug' => 'balance-transfer-from-cash-0001',
                'amount' => 20000.0,
                'type' => 0,
                'cheque_no' => null,
                'receipt_no' => null,
                'transaction_date' => now(),
                'note' => null,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'account_id' => 1,
                'created_by' => 1,
            ],
            4 => [
                'id' => 5,
                'reason' => 'Balance transfer to [IBBL-0002]',
                'slug' => 'balance-transfer-to-ibbl-0002',
                'amount' => 20000.0,
                'type' => 1,
                'cheque_no' => null,
                'receipt_no' => null,
                'transaction_date' => now(),
                'note' => null,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'account_id' => 3,
                'created_by' => 1,
            ],
            5 => [
                'id' => 6,
                'reason' => 'Balance transfer from [CASH-0001]',
                'slug' => 'balance-transfer-from-cash-0001-2',
                'amount' => 10000.0,
                'type' => 0,
                'cheque_no' => null,
                'receipt_no' => null,
                'transaction_date' => now(),
                'note' => null,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'account_id' => 1,
                'created_by' => 1,
            ],
            6 => [
                'id' => 7,
                'reason' => 'Balance transfer to [DBBL-0003]',
                'slug' => 'balance-transfer-to-dbbl-0003',
                'amount' => 10000.0,
                'type' => 1,
                'cheque_no' => null,
                'receipt_no' => null,
                'transaction_date' => now(),
                'note' => null,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'account_id' => 2,
                'created_by' => 1,
            ],
            7 => [
                'id' => 8,
                'reason' => '[AES-2] Expense payment',
                'slug' => 'aes-2-expense-payment',
                'amount' => 1000.0,
                'type' => 0,
                'cheque_no' => 'AHGF5670987',
                'receipt_no' => 'VN-001',
                'transaction_date' => now(),
                'note' => null,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'account_id' => 1,
                'created_by' => 1,
            ],
            8 => [
                'id' => 9,
                'reason' => '[AES-1] Expense payment',
                'slug' => 'aes-1-expense-payment',
                'amount' => 20000.0,
                'type' => 0,
                'cheque_no' => 'CN-00001',
                'receipt_no' => 'VN-00001',
                'transaction_date' => now(),
                'note' => null,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'account_id' => 3,
                'created_by' => 1,
            ],
            9 => [
                'id' => 10,
                'reason' => '[APP-2] Purchase Payment sent from [IBBL-0002]',
                'slug' => 'app-2-purchase-payment-sent-from-ibbl-0002',
                'amount' => 25000.0,
                'type' => 0,
                'cheque_no' => 'CN-001834',
                'receipt_no' => 'RN-00122',
                'transaction_date' => now(),
                'note' => null,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'account_id' => 3,
                'created_by' => 1,
            ],
            10 => [
                'id' => 11,
                'reason' => '[APP-3] Purchase Payment sent from [CASH-0001]',
                'slug' => 'app-3-purchase-payment-sent-from-cash-0001',
                'amount' => 30000.0,
                'type' => 0,
                'cheque_no' => 'CN-004234',
                'receipt_no' => 'RN-97854',
                'transaction_date' => now(),
                'note' => null,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'account_id' => 1,
                'created_by' => 1,
            ],
            11 => [
                'id' => 12,
                'reason' => '[APP-4] Purchase Payment sent from [DBBL-0003]',
                'slug' => 'app-4-purchase-payment-sent-from-dbbl-0003',
                'amount' => 31377.5,
                'type' => 0,
                'cheque_no' => 'CN-0043245',
                'receipt_no' => 'Receipt No-5435543',
                'transaction_date' => now(),
                'note' => null,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'account_id' => 2,
                'created_by' => 1,
            ],
            12 => [
                'id' => 13,
                'reason' => '[APR-2] Purchase Return receivable added to [CASH-0001]',
                'slug' => 'apr-2-purchase-return-receivable-added-to-cash-0001',
                'amount' => 8610.0,
                'type' => 1,
                'cheque_no' => 'CN-001',
                'receipt_no' => 'RN-012143',
                'transaction_date' => now(),
                'note' => null,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'account_id' => 1,
                'created_by' => 1,
            ],
            13 => [
                'id' => 14,
                'reason' => '[AI-1] Invoice Payment added to [CASH-0001]',
                'slug' => 'ai-1-invoice-payment-added-to-cash-0001',
                'amount' => 15000.0,
                'type' => 1,
                'cheque_no' => 'CN-001231',
                'receipt_no' => 'RN-053456',
                'transaction_date' => now(),
                'note' => null,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'account_id' => 1,
                'created_by' => 1,
            ],
            14 => [
                'id' => 15,
                'reason' => '[AI-5] Invoice Payment added to [CASH-0001]',
                'slug' => 'ai-5-invoice-payment-added-to-cash-0001',
                'amount' => 20000.0,
                'type' => 1,
                'cheque_no' => 'CN-05345',
                'receipt_no' => 'RN-42365',
                'transaction_date' => now(),
                'note' => null,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'account_id' => 1,
                'created_by' => 1,
            ],
            15 => [
                'id' => 16,
                'reason' => '[AI-6] Invoice Payment added to [DBBL-0003]',
                'slug' => 'ai-6-invoice-payment-added-to-dbbl-0003',
                'amount' => 35000.0,
                'type' => 1,
                'cheque_no' => 'CN-001',
                'receipt_no' => 'Receipt No-0001',
                'transaction_date' => now(),
                'note' => null,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'account_id' => 2,
                'created_by' => 1,
            ],
            16 => [
                'id' => 17,
                'reason' => '[AIR-2] Invoice Return payable sent from [CASH-0001]',
                'slug' => 'air-2-invoice-return-payable-sent-from-cash-0001',
                'amount' => 6163.5,
                'type' => 0,
                'cheque_no' => 'CN-52345',
                'receipt_no' => 'RN-5342',
                'transaction_date' => now(),
                'note' => null,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'account_id' => 1,
                'created_by' => 1,
            ],
            17 => [
                'id' => 18,
                'reason' => '[AC-5] Non inovice payment added to [IBBL-0002]',
                'slug' => 'ac-5-non-inovice-payment-added-to-ibbl-0002',
                'amount' => 5000.0,
                'type' => 1,
                'cheque_no' => 'CN-05435',
                'receipt_no' => 'RN-54255',
                'transaction_date' => now(),
                'note' => null,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'account_id' => 3,
                'created_by' => 1,
            ],
            18 => [
                'id' => 19,
                'reason' => '[AC-4] Non inovice payment added to [DBBL-0003]',
                'slug' => 'ac-4-non-inovice-payment-added-to-dbbl-0003',
                'amount' => 10000.0,
                'type' => 1,
                'cheque_no' => 'CN-5425',
                'receipt_no' => 'RN-5425',
                'transaction_date' => now(),
                'note' => null,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'account_id' => 2,
                'created_by' => 1,
            ],
            19 => [
                'id' => 20,
                'reason' => '[AS-1] Non purchase due sent from [DBBL-0003]',
                'slug' => 'as-1-non-purchase-due-sent-from-dbbl-0003',
                'amount' => 10000.0,
                'type' => 0,
                'cheque_no' => 'CN-5425',
                'receipt_no' => 'RN-52345',
                'transaction_date' => now(),
                'note' => null,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'account_id' => 2,
                'created_by' => 1,
            ],
            20 => [
                'id' => 21,
                'reason' => '[AS-2] Non purchase due sent from [IBBL-0002]',
                'slug' => 'as-2-non-purchase-due-sent-from-ibbl-0002',
                'amount' => 5000.0,
                'type' => 0,
                'cheque_no' => 'CN-52435',
                'receipt_no' => 'RN-54235',
                'transaction_date' => now(),
                'note' => null,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'account_id' => 3,
                'created_by' => 1,
            ],
            21 => [
                'id' => 22,
                'reason' => '[AE-2] February Payroll sent from [CASH-0001]',
                'slug' => 'ae-2-february-payroll-sent-from-cash-0001',
                'amount' => 9800.0,
                'type' => 0,
                'cheque_no' => 'CN-3535',
                'receipt_no' => null,
                'transaction_date' => now(),
                'note' => null,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'account_id' => 1,
                'created_by' => 1,
            ],
            22 => [
                'id' => 23,
                'reason' => '[AE-1] February Payroll sent from [IBBL-0002]',
                'slug' => 'ae-1-february-payroll-sent-from-ibbl-0002',
                'amount' => 12300.0,
                'type' => 0,
                'cheque_no' => 'CN-4325',
                'receipt_no' => null,
                'transaction_date' => now(),
                'note' => null,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'account_id' => 3,
                'created_by' => 1,
            ],
            23 => [
                'id' => 24,
                'reason' => '[DBBL-0001] Loan added to [DBBL-0003]',
                'slug' => 'dbbl-0001-loan-added-to-dbbl-0003',
                'amount' => 100000.0,
                'type' => 1,
                'cheque_no' => null,
                'receipt_no' => null,
                'transaction_date' => now(),
                'note' => null,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'account_id' => 2,
                'created_by' => 1,
            ],
            24 => [
                'id' => 25,
                'reason' => '[IBBL-0001] Loan added to [IBBL-0002]',
                'slug' => 'ibbl-0001-loan-added-to-ibbl-0002',
                'amount' => 100000.0,
                'type' => 1,
                'cheque_no' => null,
                'receipt_no' => null,
                'transaction_date' => now(),
                'note' => null,
                'status' => 1,
                'created_at' => '2022-05-01 05:52:35',
                'updated_at' => '2022-05-01 05:53:06',
                'account_id' => 3,
                'created_by' => 1,
            ],
            25 => [
                'id' => 26,
                'reason' => '[DBBL-0001] Loan Payment sent from [DBBL-0003]',
                'slug' => 'dbbl-0001-loan-payment-sent-from-dbbl-0003',
                'amount' => 4522.73,
                'type' => 0,
                'cheque_no' => null,
                'receipt_no' => null,
                'transaction_date' => now(),
                'note' => null,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'account_id' => 2,
                'created_by' => 1,
            ],
            26 => [
                'id' => 27,
                'reason' => '[DBBL-0001] Loan Payment sent from [DBBL-0003]',
                'slug' => 'dbbl-0001-loan-payment-sent-from-dbbl-0003-2',
                'amount' => 4522.73,
                'type' => 0,
                'cheque_no' => null,
                'receipt_no' => null,
                'transaction_date' => now(),
                'note' => null,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'account_id' => 2,
                'created_by' => 1,
            ],
            27 => [
                'id' => 28,
                'reason' => '[DBBL-0001] Loan Payment sent from [DBBL-0003]',
                'slug' => 'dbbl-0001-loan-payment-sent-from-dbbl-0003-3',
                'amount' => 4522.73,
                'type' => 0,
                'cheque_no' => null,
                'receipt_no' => null,
                'transaction_date' => now(),
                'note' => null,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'account_id' => 2,
                'created_by' => 1,
            ],
            28 => [
                'id' => 29,
                'reason' => '[DBBL-0001] Loan Payment sent from [DBBL-0003]',
                'slug' => 'dbbl-0001-loan-payment-sent-from-dbbl-0003-4',
                'amount' => 4522.73,
                'type' => 0,
                'cheque_no' => null,
                'receipt_no' => null,
                'transaction_date' => now(),
                'note' => null,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'account_id' => 2,
                'created_by' => 1,
            ],
        ]);
    }
}