<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class DemoInvoicesTableSeeder extends Seeder
{
    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        \DB::table('invoices')->delete();

        \DB::table('invoices')->insert([
            0 => [
                'id' => 1,
                'invoice_no' => '1',
                'slug' => '626d33293b3db',
                'reference' => 'Reference-001',
                'transport' => null,
                'discount_type' => 0,
                'discount' => null,
                'sub_total' => 18725.0,
                'po_reference' => 'PO Reference-1',
                'payment_terms' => 'Payment Terms-1',
                'delivery_place' => 'Dhaka, Bangladesh',
                'invoice_date' => today(),
                'note' => 'This is a note!',
                'status' => 1,
                'is_paid' => 0,
                'created_at' => now(),
                'updated_at' => now(),
                'client_id' => 5,
                'tax_id' => 2,
                'created_by' => 1,
            ],
            1 => [
                'id' => 2,
                'invoice_no' => '2',
                'slug' => '626d33af24fd8',
                'reference' => 'Reference-002',
                'transport' => null,
                'discount_type' => 0,
                'discount' => null,
                'sub_total' => 18725.0,
                'po_reference' => null,
                'payment_terms' => null,
                'delivery_place' => 'Dhaka, Bangladesh',
                'invoice_date' => today(),
                'note' => 'This is a note!',
                'status' => 1,
                'is_paid' => 0,
                'created_at' => now(),
                'updated_at' => now(),
                'client_id' => 4,
                'tax_id' => 2,
                'created_by' => 1,
            ],
            2 => [
                'id' => 3,
                'invoice_no' => '3',
                'slug' => '626d33d2aa232',
                'reference' => 'Reference-003',
                'transport' => null,
                'discount_type' => 0,
                'discount' => null,
                'sub_total' => 18725.0,
                'po_reference' => null,
                'payment_terms' => null,
                'delivery_place' => 'Dhaka, Bangladesh',
                'invoice_date' => today(),
                'note' => 'This is a note!',
                'status' => 1,
                'is_paid' => 0,
                'created_at' => now(),
                'updated_at' => now(),
                'client_id' => 5,
                'tax_id' => 2,
                'created_by' => 1,
            ],
            3 => [
                'id' => 4,
                'invoice_no' => '4',
                'slug' => '626d33fc734c9',
                'reference' => 'Reference-001',
                'transport' => null,
                'discount_type' => 0,
                'discount' => null,
                'sub_total' => 18725.0,
                'po_reference' => null,
                'payment_terms' => null,
                'delivery_place' => 'Dhaka, Bangladesh',
                'invoice_date' => today(),
                'note' => 'This is a note!',
                'status' => 1,
                'is_paid' => 0,
                'created_at' => now(),
                'updated_at' => now(),
                'client_id' => 2,
                'tax_id' => 2,
                'created_by' => 1,
            ],
            4 => [
                'id' => 5,
                'invoice_no' => '5',
                'slug' => '626d86a82bec0',
                'reference' => 'Reference-0005',
                'transport' => 500.0,
                'discount_type' => 1,
                'discount' => 561.75,
                'sub_total' => 18725.0,
                'po_reference' => 'PO Reference-0004',
                'payment_terms' => 'Payment Terms-0005',
                'delivery_place' => 'Dhaka, Bangladesh',
                'invoice_date' => today(),
                'note' => 'This is a note!',
                'status' => 1,
                'is_paid' => 0,
                'created_at' => now(),
                'updated_at' => now(),
                'client_id' => 1,
                'tax_id' => 1,
                'created_by' => 1,
            ],
            5 => [
                'id' => 6,
                'invoice_no' => '6',
                'slug' => '626d889de5502',
                'reference' => 'Reference-006',
                'transport' => null,
                'discount_type' => 0,
                'discount' => null,
                'sub_total' => 37450.0,
                'po_reference' => null,
                'payment_terms' => null,
                'delivery_place' => 'Dhaka',
                'invoice_date' => today(),
                'note' => '',
                'status' => 1,
                'is_paid' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'client_id' => 3,
                'tax_id' => 2,
                'created_by' => 1,
            ],
        ]);
    }
}